builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
    main: cmd/jsont/main.go  # Add main file path
    dir: .                   # Set base directory for build
    binary: jsont           # Set binary name
checksum:
  name_template: "checksums.txt"